[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "python3"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --no-optional"]

[phases.build]
cmds = ["cd client && npm ci --legacy-peer-deps", "cd client && npm run build"]

[start]
cmd = "npm start"
